### ISSUE TITLE
Why does systemd need privileged mode with ubuntu?

### ISSUE THREAD

**Issue by rchawathearkin** [zaunerc/codesandbox#1]
Hi Christoph

We tried your instructions on the blog with fedora and they work like a charm.
But on using ubuntu, systemd is able to run only when docker container is run in privileged mode.
Could you explain the reason?

Thanks,
Rahul

**Comment by zaunerc** [comment]
Hi Rahul,

Could you please tell me which versions of Ubuntu and Docker you are currently using?

Hints:

```
# Ubuntu
cat /etc/lsb-release
# Docker
docker --version
```

Best regards,
Chris

**Comment by rchawathearkin** [comment]
Hi Chris,

Here is the output you requested
```
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"

docker --version
Docker version 20.10.7, build f0df350
```

Thanks,
Rahul

**Comment by zaunerc** [comment]
I will be looking at this over the course of the next week.

**Comment by zaunerc** [comment]
I tried to create the same operating system environment you have mentioned. It features Ubuntu 18.04 and Docker 20.10.8 (from the official upstream package repository - https://docs.docker.com/engine/install/ubuntu/). But I am not able to reproduce the behaviour you are describing. In my environment everything works out of the box. I can start the Docker container using the following command (the `--privileged` flag is absent):

```
sudo docker run --tmpfs /tmp --tmpfs /run -v /sys/fs/cgroup:/sys/fs/cgroup:ro -p 9090:80 --name sysd --rm sysd
```

My guess is that some security related settings might have been altered in your Ubuntu environment. Maybe you can find a hint when running the Docker daemon in debug mode and taking a look at it's logs. Or maybe it has to do something with the `CAP_SYS_ADMIN` linux capability. You could try starting the container with the `--cap-add SYS_ADMIN` flag to see if this makes a difference. But only add this capability for troubleshooting purposes as this might increase the risk of security vulnerabilities.

Just for my reference:

```
vagrant@ubuntu:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
vagrant@ubuntu:~$

vagrant@ubuntu:~$ sudo docker version
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:08 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:16 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
vagrant@ubuntu:~$ 
```
